### ISSUE TITLE
Server-side error: JSON.parse is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by rye** [hybsearch/hybsearch#88]
We are getting the following server-side error on Thing3's HEAD server, (`:81`) which is not accepting jobs and crashing.

```
listening on localhost:8080
connection initiated
/hybsearch/server.js:32
		const [cmd, ...args] = JSON.parse(communique)
		                            ^

TypeError: JSON.parse is not a function or its return value is not iterable
    at WebSocket.ws.on.communique (/hybsearch/server.js:32:31)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (/hybsearch/node_modules/ws/lib/websocket.js:137:47)
    at Receiver.dataMessage (/hybsearch/node_modules/ws/lib/receiver.js:409:14)
    at Receiver.getData (/hybsearch/node_modules/ws/lib/receiver.js:347:12)
    at Receiver.startLoop (/hybsearch/node_modules/ws/lib/receiver.js:143:16)
    at Receiver.add (/hybsearch/node_modules/ws/lib/receiver.js:117:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hybsearch/server@4.0.0-beta.3 start: `./server.js "8080"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @hybsearch/server@4.0.0-beta.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-04T16_54_23_560Z-debug.log
```

@hawkrives, any ideas?

**Comment by rye** [comment]
Not actually an error… Closing.  (This was due to a deployment miss.)
